<?php
$img_description = array(
'1-penmonkey_pics1.jpg' => 'PENmonkey, designer pen case, pen pouch, pencil bag is attachable to notebooks',
'2-penmonkey_pics3.jpg' => 'PENmonkey, pen case, pen pouch, pencil bag effective and protective pen holder',
'3-penmonkey_pics5.jpg' => 'PENmonkey, pen case, pen pouch, pencil bag designed to be attachable with elastic band to notebooks',
'4-penmonkey_pics7.jpg' => 'PENmonkey, pen case, pen pouch, pencil bag designed to be attachable with elastic band to notebooks in any size',
'5-penmonkey_pics2.jpg' => 'PENmonkey, pen case, pen pouch, pencil bag designed to be attachable with elastic band',
'6-penmonkey_pics6.jpg' => 'PENmonkey, pen case, pen pouch, pencil bag colorful minimal design',
    );
?>
